# reference : https://www.docker.com/blog/how-to-dockerize-react-app/#handling-environment-variables-securely

# ------------------------
#  FRONTEND: Vite + React
# ------------------------

# Stage 1: Build the app
FROM node:24-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
