# This code snippet has been taken from Docker documentation website and later modified
# https://docs.docker.com/get-started/docker-concepts/building-images/writing-a-dockerfile/

FROM python:3.13-slim
WORKDIR /app

# Install the application dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy in the source code
COPY src ./src
EXPOSE 8080

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

# 👇 Install watchdog for reload capability
RUN pip install watchdog

# 👇 Use --reload for auto-refresh during development
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]